# Generated by Django 2.2.16 on 2022-03-31 21:50

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingridientquantity',
            options={'verbose_name': 'Количество ингридиента', 'verbose_name_plural': 'Количество ингридиентов'},
        ),
        migrations.AlterField(
            model_name='ingridientquantity',
            name='ingridient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingridient', to='recipes.Ingridient', verbose_name='Ингридиент'),
        ),
        migrations.AlterField(
            model_name='ingridientquantity',
            name='value',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Количество'),
        ),
    ]
