# Generated by Django 2.2.16 on 2022-04-04 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_auto_20220404_1911'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipeingredients',
            options={'verbose_name': 'Ингредиенты рецепта', 'verbose_name_plural': 'Ингредиенты рецепта'},
        ),
        migrations.AlterModelOptions(
            name='recipetags',
            options={'verbose_name': 'Теги рецепта', 'verbose_name_plural': 'Теги рецепта'},
        ),
    ]
