# Generated by Django 2.2.16 on 2022-04-10 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_auto_20220410_2145'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RecipeFavorite',
        ),
    ]
