# Generated by Django 2.2.16 on 2022-04-04 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0010_auto_20220404_2022'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipeingredients',
            options={'ordering': ['recipe'], 'verbose_name': 'Ингредиенты рецепта', 'verbose_name_plural': 'Ингредиенты рецепта'},
        ),
        migrations.AlterModelOptions(
            name='recipetags',
            options={'ordering': ['recipe'], 'verbose_name': 'Теги рецепта', 'verbose_name_plural': 'Теги рецепта'},
        ),
    ]
