# Generated by Django 2.2.16 on 2022-04-05 19:44

from django.db import migrations, models
import recipes.utils


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0013_auto_20220405_2106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=recipes.utils.get_upload_path, verbose_name='Картинка'),
        ),
    ]
